### ISSUE TITLE
Offer an "immutable" tag on Docker Hub

### ISSUE THREAD

**Issue by RothAndrew** [jenkinsci/docker#1036]
## What I saw

Several days ago, I chose the `jenkins/jenkins:2.249.3-lts-centos7" tag as it seemed to be a pinned version. However, that tag was overwritten today, which tells me that that tag is not treated as immutable.

## What I expect

I expect to be able to choose a tag in the `jenkins/jenkins` docker repo that will not be changed after I have chosen (and tested) it.

**Comment by dduportal** [comment]
Hello @RothAndrew , the challenge here is that updates from the upstream image (centos 7 in this case) should be taken in account. The reason is that the Jenkins Docker Image has not only Jenkins as dependency, but also others packages.

This is the reason why the tags might be updated, to ensure the safety of the image content.

In order to solve your issue, what do you think about using [Docker Digest](https://docs.docker.com/engine/reference/commandline/images/#list-image-digests) instead of tag, to ensure that the image you are using is always the same?

=> Digest are always available even if the tag is updated to a new image (e.g. a new digest), as per the official and latest Docker announcements: https://www.docker.com/blog/docker-hub-image-retention-policy-delayed-and-subscription-updates/ .

**Comment by RothAndrew** [comment]
Aren't untagged digests garbage collected periodically?

**Comment by dduportal** [comment]
As I understand, the garbage collection is done on the "Hub" part, which is the "front" part of the whole system. The "back" part is a "registry" service which your docker (or container) engine are communicating with when pulling/pushing.

Let me ask for confirmation/documentation to official Docker employee and I'll get back to you here to be sure I'm not saying wrong things :)

**Comment by dduportal** [comment]
It look likes (no documentation whatsoever right now) that the garbage collecting deletes digest ONLY if an explicit tag deletion had been done through the REST API.

When overriding a tag, there is no "DELETE": the DockerHub API tracks the references of the old and new digests.

It means that you can safely use the digest to keep your images stable over time. It is important to note that even if the Docker Hub starts to cleanup, it's at least 1 year before the images could be removed: if you keep the same Jenkins image without update for 1 year, you are putting your infrastructure at risK

Speaking of which you might be interested in https://www.updatecli.io/docs/resources/docker_digest/ , which is the tool we are using on the Jenkins infrastructure to help us maintaining our Docker images/helm chart up to date. You can see it as a tool to be run by your Jenkins instance regularly (daily, weekly, monthly), and that will take care of retrieveing the latest digest of a given tag, and update the Dockerfile/helm chart you specify. If you are using GitHub, it can even open a PR to help you: you can keep a human validation and update only when you need it, but it automates the "tedious" part so you can focus on your update.

**Comment by timja** [comment]
Ours tags are currently not modified as far as I can tell except for the windows one.

maybe there was a one off issue for that image.

Happy to re open if someone sees differently
