### ISSUE TITLE
Jenkins Master doesn't use all the available memory

### ISSUE THREAD

**Issue by esfomeado** [jenkinsci/docker#1171]
### Version report

Jenkins and plugins versions report:

```
Jenkins Version: 2.289.3
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
AWS Fargate (jenkins/jenkins:2.289.3)
```

### Reproduction steps

- I'm running the Jenkins docker image on AWS Fargate and I have setup the instance with 8GB of memory but the Jenkins master instance is only using 2GB. Any way to work around this?

### Results

Expected result:

Should use all available memory.

Actual result:

Uses only 25%

**Comment by dduportal** [comment]
Hello @esfomeado , when you say "use all available memory", how do you measure it, and why do you expect it to behave like this?

Could you give us more details, such as how much builds are running, if you see Jenkins crashing or not behaving as expected?

It seems that you are using the latest LTS 2.289.3, which defaults to using JDK8: it means that you should define the 2 following JVM flags `-XX:+UseCGroupMemoryLimitForHeap` and `-XX:+UnlockExperimentalVMOptions` to the `JAVA_OPTS` variable (see. https://github.com/jenkinsci/docker#passing-jvm-parameters), and avoid defining ANY `XmX` or `Xms` options, so that the JVM will define what it is best for itself in the respect of the container's resource limitations.

You can read more about JDK8 and containers here: https://blogs.oracle.com/java/post/java-on-container-like-a-pro.

If you switch to JDK11, the 25% make sense as by default the JVM allocates ~25% of the container's limit (or machine memory) for the heap. It does not mean that the rest of the memory won't be used when Jenkins has to manage a big pile of builds for instance.
You can try to execute with the Java flag `-XshowSettings:vm` to validate how much heap is allocated at startup in any cases.
