### ISSUE TITLE
Jenkins container won't start

### ISSUE THREAD

**Issue by Gabbyr** [jenkinsci/docker#129]
hi - I am getting this when trying to run Jenkins container :

[FATAL] Executing child process '/usr/local/bin/jenkins.sh' failed: 'Permission denied'

anyone seen it before ?

**Comment by ndeloof** [comment]
What command are you using to start the container ?

**Comment by carlossg** [comment]
please provide the information requested in https://github.com/jenkinsci/docker/blob/master/CONTRIBUTING.md

**Comment by JakeStoeffler** [comment]
@Gabbyr I encountered this same issue but was able to work around it. I was running `docker run -p 8080:8080 -v $PWD/jenkins_home:/var/jenkins_home jenkins` and it turns out I had to create the `jenkins_home` directory in the current directory prior to running this command, otherwise I got the permission denied error. For some reason, if I didn't create it myself first, it was being created under root ownership.

**Comment by Gabbyr** [comment]
Thank you very much. I will try this out soon and will provide feedback.
Had to move to other things for a while and now back to docker.

**Comment by anthonygreen** [comment]
See: https://groups.google.com/d/msg/docker-user/61U2oA85bKg/iohhl0C1EwAJ
I think it might be helpful to provide some documentation on how to use this image in other circumstances.
Maybe if the maintainers could start the wiki and people could contribute ideas

**Comment by ndeloof** [comment]
that's a generic docker usage issue, unrelated to jenkins. 
If you want to give some detailed usage guidance, feel free to create an usage.md file and propose for contribution

**Comment by carlossg** [comment]
The problem with the error

    [FATAL] Executing child process '/usr/local/bin/jenkins.sh' failed: 'Permission denied'

Is that  `/usr/local/bin/jenkins.sh` doesn't have world executable permissions (bad local build maybe?)

This can be checked with 

    docker run --rm -ti --entrypoint sh jenkins -c "ls -alF /usr/local/bin/"

and the output should show `jenkins.sh` with 777 permissions. If that is not the case, check the `jenkins.sh` permissions in the local folder where you are building from. They should be correct after a git clone though.

**Comment by buenjybar** [comment]
I changed a little bit the Dockerfile and it seems to work like that 
```
... 
USER ${user}
COPY jenkins.sh /usr/local/bin/jenkins.sh

USER root
RUN chmod +x /usr/local/bin/jenkins.sh

USER ${user}
...
```

with regards,

**Comment by carlossg** [comment]
@buenjybar were you running from a repo image or you built it yourself?

**Comment by buenjybar** [comment]
@carlossg, i copied the Dockerfile and built it by myself.

**Comment by carlossg** [comment]
It didn't start because you don't have the correct permissions in the files. They are correct in the git repo

**Comment by buenjybar** [comment]
ok i will double check that ! 

thanks a lot.

**Comment by evaldasou** [comment]
I have the same issue here:
`[FATAL tini (7)] exec /usr/local/bin/jenkins.sh failed: Permission denied`

1. I have tried @buenjybar  workaround, but issue is still the same.
2. docker build started on freshly cloned jenkinsci/docker repository. 
3. have tried chmod 777 *.sh - still issue is the same @carlossg .

Maybe the issue is, because I'm trying to upgrade from Jenkins 2.32.1 to 2.32.2? I'm keeping jenkins_home volume as is, - without a touch.

Everything works fine for 2.32.1 image I built few weeks ago, not for fresh 2.32.2

**Comment by carlossg** [comment]
you need to check what are the permissions of /usr/local/bin in the container 

```
docker build -t jenkins .
docker run -ti --rm jenkins ls -laF /usr/local/bin/jenkins.sh
```

**Comment by evaldasou** [comment]
thanks @carlossg 
seems to be good, no ? :
`ls -laF /usr/local/bin/jenkins.sh
-rwxr-xr-x 1 root root 1210 Feb  9 16:11 /usr/local/bin/jenkins.sh*`

**Comment by carlossg** [comment]
what command do you run and what's the full output ?

**Comment by evaldasou** [comment]
@carlossg full output:
`docker run -it --rm jenkins-k8s-master ls -laF /usr/local/bin/jenkins.sh
-rwxr-xr-x 1 root root 1210 Feb  9 16:11 /usr/local/bin/jenkins.sh*`

**Comment by evaldasou** [comment]
@carlossg thanks for You help, I have found my issue!
I have been additionally installing `build-essential` package with jenkins dockerfile... somehow it made it fail to start!
