### ISSUE TITLE
2.346.3 LTS Docker image susceptible to JDK-8292260

### ISSUE THREAD

**Issue by basil** [jenkinsci/docker#1441]
### Jenkins and plugins versions report

`jenkins/jenkins:2.346.3` Docker image

```
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment Temurin-11.0.16+8 (build 11.0.16+8)
OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (build 11.0.16+8, mixed mode)
```

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22.04.1 LTS x86_64

### Reproduction steps

Run `java -version`.

### Expected Results

The version should be one that is free of known issues, such as 11.0.15 or 11.0.16.1.

### Actual Results

Observe that the version is 11.0.16, which is susceptible to a major regression, [JDK-8292260](https://bugs.openjdk.org/browse/JDK-8292260).

### Anything else?

Observations:

- We absolutely want this to be fixed in the next weekly release.
- I do not think we want to ship 2.361.1 until this is fixed.
- We may possibly want to issue a new 2.346.x release with this fix as well.

CC @dduportal @MarkEWaite @timja

**Comment by basil** [comment]
At the time of this writing, https://adoptium.net contains the following notice:

> **18th of August 2022:** Upstream OpenJDK has released fixes to [resolve a regression](https://mail.openjdk.org/pipermail/jdk-updates-dev/2022-August/016460.html) in some of the July releases. We are working to release 11.0.16.1+1 and 17.0.4.1+1. As usual, you can continue to track progress [**by platform**](https://github.com/adoptium/adoptium/issues/153) or [**by detailed release checklist**](https://github.com/adoptium/adoptium/issues/152).

At the time of this writing the 11.0.16.1+1 and 17.0.4.1+1 build tarballs have been published, but the Docker images have not. I think as soon as the Docker images are published we will want to kick off Dependabot updating and backporting.

**Comment by MarkEWaite** [comment]
Thanks for catching that change!  Yes, I think that we should assure that Jenkins 2.361.1 includes the updated JDK.  I'm less confident that we need to issue a new 2.346.x release, since Jenkins core version won't change.  We may want to release a new Docker image for the controller and for any agent images that use 11.0.16 or 17.0.4, though I'm not sure how we would assign a number to the Docker container images.  They would be for Jenkins 2.346.3 but would revise the JDK contained in the image.

**Comment by dduportal** [comment]
Many thanks @basil for this due diligence for this topic! ❤️ 

- About the LTS line, what do you think about releasing this change with a "package number like" suffix such as `2.346.3-2` (assuming that `2.346.3` was implicitly a `2.346.3-1` ) ? The idea is the following:
  - We do not want any Jenkins LTS release to be triggered for this change (if we want: then no problem because the `2.346.4` would solve the problem)
  - We want users pinning to one of the `lts`, `lts-jdk11`, `lts-almalinux` etc. image tags to see a new version with the fix
  - We want users to be able to pin to a `2.346.3-2` (etc.) tag if they want
  - We do not want to change the images for users pinned to a `2.346.3` tag

- Let's go for the weekly and next-LTS updates (I assume in 2 PRs: one on the "master" branch, and then a backport to the upcoming stable LTS branc: Am I understing correctly @basil ?).

**Comment by timja** [comment]
sounds fine 👍 

Last time something like this happened we did cut a whole new release of Jenkins but it does seem overkill for packaging

**Comment by basil** [comment]
> About the LTS line, what do you think about releasing this change with a "package number like" suffix such as 2.346.3-2 (assuming that 2.346.3 was implicitly a 2.346.3-1)?

This sounds great! To be clear, I am OK with either the overkill solution of cutting a whole new release of Jenkins, or the "package number like" suffix, with no strong preference. I am happy with whatever the consensus is, so long as we provide relief to end users who are impacted by the issue.

> Let's go for the weekly and next-LTS updates (I assume in 2 PRs: one on the "master" branch, and then a backport to the upcoming stable LTS branc: Am I understing correctly @basil ?).

Yes exactly. We did have a `stable-2.346` branch because requiring Java 11 forced us to have a separate branch for Java 8 support. I'm not sure we ever reached a _decision_ to have a `stable-2.361` branch, but I did advocate for that, while leaving the decision up to the maintainers. In any case, my concern is mainly that we deliver a working JDK in 2.361.1 LTS, and if the implementation of that is a `stable-2.361` branch (my preference) that would be great, but if the implementation of that is the status quo of using the main branch, I am fine with that as well.

**Comment by dduportal** [comment]
I'm starting with 2 PRs for the upcoming weekly (in the main branch, 1 for JDK11 patch, the other for JDK17).

**Comment by dduportal** [comment]
First concern: the Docker images here are retrieving the JDK from the `eclipse-temurin` Docker images, which are not up to date with the patch versions.

Is there any concern if I switch to the retrieval of the tarball instead?

**Comment by basil** [comment]
The current implementation of pulling the files out of the Docker image is effectively a roundabout way of fetching the build tarball, as the tarball is first extracted into the upstream Docker images when the upstream Docker images are built, and then we take the extracted files from the upstream Docker image.

That having been said, I think a benefit of the current implementation is that we get Dependabot updates with low effort. If we used the tarballs, there is probably a way to keep them up-to-date with Updatecli but it might be more effort.

I am not particularly attached to the current implementation but I have no problems with it either. It works just fine. I was not specifically advocating for a reimplementation to switch from Docker images to consuming the tarballs directly. That might be more work that we could avoid by waiting (hopefully a day or two at most?) for Adoptium to publish new Docker images.

**Comment by MarkEWaite** [comment]
I'd prefer to wait a day or two and let Adoptium publish the new Docker images.  I like the dependabot tracking of updates.

**Comment by dduportal** [comment]
Thanks @MarkEWaite for the PRs:

- JDK17 for weekly: https://github.com/jenkinsci/docker/pull/1447
- JDK11 for weekly: https://github.com/jenkinsci/docker-agent/pull/274 (not merged as the armv7 package is not available)

**Comment by dduportal** [comment]
> The current implementation of pulling the files out of the Docker image is effectively a roundabout way of fetching the build tarball, as the tarball is first extracted into the upstream Docker images when the upstream Docker images are built, and then we take the extracted files from the upstream Docker image.
> 
> That having been said, I think a benefit of the current implementation is that we get Dependabot updates with low effort. If we used the tarballs, there is probably a way to keep them up-to-date with Updatecli but it might be more effort.
> 
> I am not particularly attached to the current implementation but I have no problems with it either. It works just fine. I was not specifically advocating for a reimplementation to switch from Docker images to consuming the tarballs directly. That might be more work that we could avoid by waiting (hopefully a day or two at most?) for Adoptium to publish new Docker images.

I share the same feeling. My question is raised for the sake of challenging the choice of using Docker images: the current trade-off is delaying availability of new JDK builds (JDK11 is currently waiting for armv7 for instance) at the benefit of low-cost update maintenance as you stated.

**Comment by dduportal** [comment]
Unless someone disagree (I could have misunderstood), I'm started to work on backporting these changes to `stable-2.346`. That means I'l first have to revert some of the changes to this branch so that it can build JDK11 and JDK17 images again (cc @timja for info).

**Comment by dduportal** [comment]
Ref. `2.361.1` (upcoming September LTS line), Ping @timja @MarkEWaite do you agree with @basil proposal about using stable branches + backporting changes?

If yes, may I create it by forking from the `2.361` weekly, and then we can start backporting changes that happenned since on the `master` branch, including the 2 JDK updates there?

**Comment by timja** [comment]
I feel like the build process should be re-worked first before we start using branches generally.

Currently if the master branch runs it will publish those images anyway and because it is run on a schedule you can easily miss to run the backport job.

and this should really move to release.ci.jenkins.io so that it's triggered by the release job rather than on a separate CI instance

**Comment by dduportal** [comment]
> I feel like the build process should be re-worked first before we start using branches generally.
> 
> Currently if the master branch runs it will publish those images anyway and because it is run on a schedule you can easily miss to run the backport job.
> 
> and this should really move to release.ci.jenkins.io so that it's triggered by the release job rather than on a separate CI instance

Absolutely!

**Comment by dduportal** [comment]
Backports to LTS 2.346 line:

- https://github.com/jenkinsci/docker/pull/1449
- https://github.com/jenkinsci/docker/pull/1450

**Comment by dduportal** [comment]
@timja @MarkEWaite The stable branch is ready to be release under the new tag `2.346.3-2`.

What steps are required before triggering: is there a changelog update to draft for review? Is there something else?

**Comment by MarkEWaite** [comment]
I think that the changelog or upgrade guide entry can wait until after the release is available.

**Comment by dduportal** [comment]
> I think that the changelog or upgrade guide entry can wait until after the release is available.
> 
> If we're ready, let's build it.

👍 I'm proceeding with the release then (unless someone disagree)

**Comment by timja** [comment]
GO GO GO

**Comment by dduportal** [comment]
As expected the publish script fails on trusted.ci with a weird error while it works on my machine 🤦 
Currently trying dry_run: I might have to publish more code directly to the stable branch to hotfix the publication script: expect delivery most probably tomorrow

**Comment by dduportal** [comment]
Images have been published: https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=2.346.3-2 

We can start writing changelog with the following:

- Dependencies:
  - Bump debian base images to version 20220822  
  - Bump Alpine base images to 3.16.2
  - [Use JDK 11.0.16.1 instead of JDK 11.0.16](https://github.com/jenkinsci/docker/commit/10a7911a6932b453c8abe37e787acafb17cd8ed4)
  - [Use JDK 17.0.4.1 instead of JDK 17.0.4](https://github.com/jenkinsci/docker/commit/1693cc2cb2da2be5e4a100c3146a62ed28221482)
