### ISSUE TITLE
 Upgrading Jenkins. Failed to update the default Update Site 'default'. Plugin upgrades may fail.

### ISSUE THREAD

**Issue by sameer1046** [jenkinsci/docker#1455]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux

### Reproduction steps

 docker run -p 8000:8080  jenkins/jenkins:latest-jdk11

### Expected Results

ssl certificate issue  of jenkins plugin update site should not be there

### Actual Results

 WARNING hudson.model.UpdateCenter#updateDefaultSite: Upgrading Jenkins. Failed to update the default Update Site 'default'. Plugin upgrades may fail.
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by MarkEWaite** [comment]
I can't duplicate the issue as reported.  Steps I tried:

1. Use Debian testing running `Docker version 20.10.17+dfsg1, build 100c701` to start `docker run -p 8000:8080 jenkins/jenkins:latest-jdk11`
2. Choose to install plugins from the setup wizard
3. Confirm that the plugins install as expected

You'll need to provide more details so that others can duplicate the issue.

It is common that operating systems that have not been updated may have issues with SSL connections to modern HTTPS servers.  Please he sure that your operating system has the latest patches installed.
