### ISSUE TITLE
Windows Tags

### ISSUE THREAD

**Issue by Jonny-vb** [jenkinsci/docker#1489]
### Describe your use-case which is not covered by existing documentation.

I'm assuming this has been discussed previously somewhere, but I can't find anything about it.
Why can we not specify windows tags by version? For linux based containers, each jenkins version gets its own tag, as well as latest. Ideally we would get the same for windows. This would make it a lot easier to see if there is a new base jenkins version when we pull the latest image to do an upgrade (especially as the image seems to constantly get updates without jenkins changing - I assume these are pulled in from the windows base image...?), or stick to specific LTS releases if needed.

**Comment by lemeurherve** [comment]
Reopening until validation with the next Weekly and LTS releases in two days.

**Comment by lemeurherve** [comment]
Tags containing the Jenkins version are now published, allowing to use and pin a specific Jenkins version, see images published since today: https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=windows

#### Tags before (Java 11 only for Windows releases < 2.431):
- jdk11-hotspot-windowsservercore-2019
- windowsservercore-2019 (short tag default JDK)

#### Tags now (Java 17, default JDK since Windows release 2.431):
- 2.432-jdk17-hotspot-windowsservercore-ltsc2019
- jdk17-hotspot-windowsservercore-ltsc2019
- 2.432-windowsservercore-ltsc2019 (short tag default JDK)
- windowsservercore-ltsc2019 (short tag default JDK)

A Java 11 image is published again since this weekly release 2.432, but since it's not the default JDK anymore there is no more "short" tags for it:
- 2.432-jdk11-hotspot-windowsservercore-ltsc2019
- jdk11-hotspot-windowsservercore-ltsc2019

> [!Warning]
> Notice that "ltsc" has been added to the tag name.
> Previous releases contained only "2019" and were based on `1809` Temurin images anyway, cf #1775
