### ISSUE TITLE
run Docker in host via docker.sock

### ISSUE THREAD

**Issue by Seguret** [jenkinsci/docker#1510]
### Describe your use-case which is not covered by existing documentation.

i am trying to use awscli docker on my host machine, but docker sock doesn't seem to communicate with host.

I get the error "docker not found"
how can i solve?
![image](https://user-images.githubusercontent.com/53990514/201485309-85bae40f-57e6-4105-8563-1b129bcbba85.png)

**Comment by dduportal** [comment]
Hi @Seguret , this issue tracker is for reporting issues or feature requests scoped to the Jenkins Docker image.

But your problem seems either with the [Docker Pipeline plugin](https://plugins.jenkins.io/docker-workflow/) usage or a more general problem with both Jenkins in Docker with the aformentioned plugin.

You should open a topic on the [Jenkins Community Forum](https://community.jenkins.io) to get broader help from the community (compared to only maintainers here). Don't hesitate to mention me in the forum (as I can help).

Specifically, the error message you shared in the screenshot is not related to the `docker.sock` socket neither to any `"docker not found"`, but it is a syntax error in your pipeline. As per https://www.jenkins.io/doc/book/pipeline/syntax/#agent-parameters (sub section `docker`), you must specify an `image` attribute in your `agent { docker { ... } }` block otherwise Docker cannot know start a container.

**Comment by Seguret** [comment]
this is not a syntax error. this is my pipeline:

![image](https://user-images.githubusercontent.com/53990514/201536782-77aeb271-9e75-460c-9173-1acd63dce97a.png)
this pipeline is taken from the official documentation: https://www.jenkins.io/doc/book/pipeline/docker/

![image](https://user-images.githubusercontent.com/53990514/201536747-9eca07b4-ef45-4692-91d0-e3de095d12cb.png)
