### ISSUE TITLE
Unnecessary VOLUME statement makes customization awkward

### ISSUE THREAD

**Issue by hickeng** [jenkinsci/docker#152]
Having /var/jenkins_home specified as a volume via the dockerfile makes customization awkward, and seems to add little utility.

Consider the following cases, and note that the run instructions for the image explicitly recommend one of the first two options, and imply that the jenkins metadata is non-persistent otherwise:
1. -v /var/jenkins_home specified - renders the VOLUME statement pointless
2. -v /some/where:/var/jenkins_home - explicit intent, renders the VOLUME statement pointless
3. not specified - to reuse the volume data after image update you need --volumes-from and some logic around container names/ids to hand the volumes over prior to deleting the old container.

The last case is the only one where the statement adds any value, and doesn't seem to add enough value over a pair of copy commands to be worth the extra complexity for customization.

Please can we have the VOLUME command removed so that it massively simplifies the process of building custom jenkins images.

**Comment by ndeloof** [comment]
declaring jenkins_home as a VOLUME make it clear this one has to be persisted and can't just be setup in the image. So the value is also related to the metadata it involves.

Please let us know how it prevent you to customize the image the way you expect .

**Comment by hickeng** [comment]
It inhibits use of the jenkins CLI or existing scripts/utilities for doing configuration such as site or project preparation without ensuring that the modified files (and only the modified files) are copied over to /usr/share/jenkins/ref

It's not that it can't be done, but it's onerous and only needed because of that VOLUME statement. 
The statement does make it clear where jenkins stores it's config and data, but setting that up in the image is **exactly** what I need to do. Anything else increases either the image maintenance overhead or the knowledge burden at point of execution to a point where it's not viable (internal CI-as-a-service model with a high degree of flux).

My main complaint is that it's very, very easy to add a VOLUME at runtime, but impossible to take one away if specified in the Dockerfile. That asymmetry means this is actually an issue on numerous images where the authors assumptions don't address all usage patterns. Of course I could just duplicate the Dockerfile without the statement and push yet another jenkins image, but that just adds to potential confusion as to what the differences are and why we're not using the official image.

**Comment by carlossg** [comment]
so you just want to run with the jenkins home not in a volume?

**Comment by ndeloof** [comment]
If you use CLI or UI to setup JENKINS_HOME content, then you won't be able to share this with others who want this folder to be persistent. The `ref` directory was designed for this purpose. For sure this require to make a manual copy, but this ensure this content will be created as expected on container created from your image.

If we let you create content in JENKINS_HOME in the image, then it will only be available when the container is created without an explicit bind mounted volume.

**Comment by hickeng** [comment]
Good point - I'd forgotten that explicit bindmounts don't copy the contents over from the mount point. Drat, now I'm torn between consistent behaviour and ease of use.
Perhaps a jenkins-ref.sh script that starts jenkins with JENKINS_HOME=/usr/share/jenkins/ref for use in customization steps? I'll admit I've not had any time to consider ramifications of that.

**Comment by ndeloof** [comment]
JENKINS_HOME do contain both files you want to share and some you don't want : secret.key, various log files, queue items, etc. You really need to select which of them you want to use as `ref`. That's not trivial for sure, but one-does-all JENKINS_HOME isn't something we can address here.

**Comment by libinglong** [comment]
I can not agree more about hickeng's opinion. Anyone who want to save the data do not need to know there is a volume command in dockerfile. Actually does the docker build really need the command? This is a bad command, just like ENV.
Because we can not undeclare the command when we entend the origin image.

I want to create a image which has a specified api token. And I do not need the jenkins store any job and build data. Actually I will remove any job and build data. Why? Jenkins in my scene is just a executor. I deploy it in kubernetes. I do not  want to add pvc with jenkins. I use if unstatefully so we affort no effort on it.

**Comment by libinglong** [comment]
I can not agree more about hickeng's opinion. Anyone who want to save the data do not need to know there is a volume command in dockerfile. Actually does the docker build really need the command? This is a really a bad command, just like ENV.
Because we can not undeclare the command when we entend the origin image.

I want to create a image which has a specified api token. And I do not need the jenkins store any job and build data. Actually I will remove any job and build data. Why? Jenkins in my scene is just a executor. I deploy it in kubernetes. I do not  want to add pvc with jenkins. I use it statelessly so I put hardly any effort into it.

Finally I find my way to reslove.


```dockerfile
FROM jenkins/jenkins:lts-jdk11
# any other code
ENV JENKINS_HOME=/var/custom/jenkins_home
USER root
RUN mkdir -p $JENKINS_HOME
RUN chown jenkins:jenkins $JENKINS_HOME
USER jenkins
```

**Comment by libinglong** [comment]
Finally I find my way to reslove.


```dockerfile
FROM jenkins/jenkins:lts-jdk11
# any other code
ENV JENKINS_HOME=/var/custom/jenkins_home
USER root
RUN mkdir -p $JENKINS_HOME
RUN chown jenkins:jenkins $JENKINS_HOME
USER jenkins
```
