### ISSUE TITLE
manifest not found

### ISSUE THREAD

**Issue by aizzycb** [jenkinsci/docker#1565]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

CentOS 7 from AWS Marketplace
ami-05a36e1502605b4aa
us-east-2 region
CentOS-7-2111-20220825_1.x86_64-d9a3032a-921c-4c6d-b150-bde168105e42

### Reproduction steps

1. Newly created server run the below:
yum install epel-release -y
yum install -y docker
yum check-updates
yum clean all

2. Ran the following after yum completes:
export PATH=/usr/bin:/sbin
sed -i 's/\(--selinux-enabled\) /\1=false /g' /etc/sysconfig/docker /etc/sysconfig/docker
systemctl enable docker
systemctl start docker

3. Docker version:
![image](https://user-images.githubusercontent.com/92382758/217619129-70e8aeb1-1aa6-48b3-8823-79911c795c58.png)

4. Run docker pull jenkins/jenkins:lts-jdk11 from documentation. Also tried other tags according hub.docker.io, same error message.
![image](https://user-images.githubusercontent.com/92382758/217619946-5fe3a363-ff8b-4d25-b39c-e27d99953e6b.png)

### Expected Results

Similar to the Alpine pull, expect the image to be pulled down but it's not.
![image](https://user-images.githubusercontent.com/92382758/217619818-6f4be7a4-ddee-4523-888c-4349b2479b13.png)

### Actual Results

![image](https://user-images.githubusercontent.com/92382758/217619612-26285c10-7e9d-4c9d-a0c3-a4b58d4b3915.png)

### Anything else?

I could be doing something wrong. I have an automated build that has been working, but stopped working 1/31/2023. I have tested on a CentOS7 build on VMWare, Azure and AWS, same results on each cloud. The below image was against Azure image:
![image](https://user-images.githubusercontent.com/92382758/217621204-2f60a551-6684-48f6-81d6-19171b57c428.png)

**Comment by dduportal** [comment]
Hi @aizzycb , this is because you are using a combination of 3 (really) outdated systems:

- CentOS 7, despite not End Of life, is in "maintenance" mode only: https://wiki.centos.org/About/Product
- Docker 1.13 is so old that it's not even mentionned anymore in the usual EOL website (https://endoflife.date/docker-engine)

=> you have to follow the official Docker instruction to get a recent Docker version: https://docs.docker.com/engine/install/centos/ . This recent version will be able to read the new OCI manifest format deployed on the DockerHub recently (as announced in https://www.docker.com/blog/announcing-docker-hub-oci-artifacts-support/).

**Comment by aizzycb** [comment]
Got it. Let me refactor this to include latest Docker version. Thanks!

**Comment by dduportal** [comment]
> Got it. Let me refactor this to include latest Docker version. Thanks!

You are welcome. I'm closing this issue as it seems related to your environment: feel free to reopen if you keep having the issue with a recent version of Docker.

**Comment by eric-gagnon** [comment]
Same here under Redhat 7 and default docker package that are unquestionably outdated and I will adress that. I temporarily fixed the issue by using a slightly older build (jenkins/jenkins:2.361-jdk11 instead of lts).
