### ISSUE TITLE
Allow container build immediately after publication to repo.jenkins-ci.org

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/docker#1671]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins most recent releases
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux with docker

### Reproduction steps

1. Immediately after a Jenkins core release, attempt to build the container image for that release, it will fail if the release is not yet available on get.jenkins.io

### Expected Results

Container build should succeed if the build is available on repo.jenkins-ci.org, whether or not it is available on get.jenkins.io

### Actual Results

If the build is not available on get.jenkins.io, it fails the container creation job

### Anything else?

N/A

**Comment by timja** [comment]
revert back to using artifactory? it's not like we do a huge amount of builds?

**Comment by dduportal-cloudbees** [comment]
> revert back to using artifactory? it's not like we do a huge amount of builds?

Parallelization of steps is crucial during security advisories as it we re-discovered today (e.g. starting Docker image build as soon as possible).

The change of downloading from mirrors instead of artifactory means that we have to wait for the whole "packaging" build to finish before starting the Docker image build (because mirrors must have the war).
Reverting to the old setting means that Docker image can be built in parallel of the packaging build, as the "release" build is the only requirement.

The amount of data we download from artifactory is nothing in this case (1/2 full WAR download per week) so it should not be an issue for the Artifactory bandwidth.
