### ISSUE TITLE
curl from plugins.sh should set timeouts and retries

### ISSUE THREAD

**Issue by bodepd** [jenkinsci/docker#198]
Seeing network connection hang while trying to install plugins (about 1/3 of the time).
Should add --retry and --retry-max-time.

**Comment by mnarusze** [comment]
I also have encountered timeouts and connections being reset several times. Instead of passing additional curl parameters which don't deal with the latter, I would suggest putting download in a loop which would retry the command until a file is present or until a reasonable amount of retries occurs.

**Comment by cbuckleytbi** [comment]
Submitted https://github.com/jenkinsci/docker/pull/274

**Comment by carlossg** [comment]
#274 merged
