### ISSUE TITLE
Behavior of install-plugins.sh not in line with Plugin Mgt User Interface

### ISSUE THREAD

**Issue by jmMeessen** [jenkinsci/docker#327]
The `install-plugins` script searches and installs the dependencies of a plugin installation request. This makes the configuration very readable and works the same way as the Plugin Maintenance User Interface. 

But the script uses also the dependency's version information contained in the parent plugin. Although logical, this leads to inconsistencies in the relationship between plugins. For example, on a blank system, installing the `github-oauth` plugin with the script (and letting it search the dependencies) ends with a system where exceptions are thrown in the admin UI.

The plugin management user interface downloads the **latest** version of the dependencies. Using this method, the above mentioned test case works.

_I recommend adapting the `install-plugins.sh` to install always the latest version of the parent plugin and of the dependencies just as the Plugin Management User Interface does._

Should a user want to "pin" the plugin versions, he should use the `plugins.sh` after having taken the snapshot of the plugins configuration with the curl command on a working hand tuned system.

**Comment by ydubreuil** [comment]
I think the problem comes from the fact the script ignores optional dependencies. If a plugin has an optional dependency which is required dependency for another plugin, the downloaded plugin can be too old to fulfill the optional dependency of the former plugin. This prevents Jenkins to start the plugin with the optional dependency.

I'm experimenting another approach to download plugins in https://github.com/jenkinsci/blueocean-plugin/pull/403 which is based on Maven which has the real knowledge of the dependency tree of each plugin.

**Comment by netrounds-fredrik** [comment]
By coincidence I have stumbled upon the same issue and have created a PR just now. See https://github.com/jenkinsci/docker/pull/328

**Comment by jmMeessen** [comment]
@ydubreuil I am not convinced that the issue comes from the optional dependencies. 

In the case of the `github-oauth` pluging, the unwanted behavior starts from the top level of the tree as can be seen in the following examples in the build output extract below: the `github-oauth` depends following the script on `mailer:1.4` and `git:2.0.3`, while the User Interface picks up the following "latest" dependencies `mailer:1.17` and `git:2.5.3`.

I had only a cursive read of the script though.

Jmm

```
Step 2 : RUN /usr/local/bin/install-plugins.sh github-oauth:0.24
 ---> Running in 8d9a10374e5a
Creating initial locks...

Analyzing war...

Downloading plugins...
Downloading plugin: github-oauth from https://updates.jenkins.io/download/plugins/github-oauth/0.24/github-oauth.hpi
 > github-oauth depends on mailer:1.4,git:2.0.3,github-api:1.69
Downloading plugin: mailer from https://updates.jenkins.io/download/plugins/mailer/1.4/mailer.hpi
Downloading plugin: git from https://updates.jenkins.io/download/plugins/git/2.0.3/git.hpi
Downloading plugin: github-api from https://updates.jenkins.io/download/plugins/github-api/1.69/github-api.hpi
 > mailer has no dependencies
 > github-api has no dependencies
 > git depends on parameterized-trigger:2.4;resolution:=optional,git-client:1.6.3,token-macro:1.10;resolution:=optional,credentials:1.10,multiple-scms:0.2;resolution:=optional,scm-api:0.2,ssh-credentials:1.6.1,promoted-builds:2.15;resolution:=optional
Skipping optional dependency parameterized-trigger
Skipping optional dependency token-macro
Downloading plugin: git-client from https://updates.jenkins.io/download/plugins/git-client/1.6.3/git-client.hpi
Skipping optional dependency multiple-scms
Downloading plugin: credentials from https://updates.jenkins.io/download/plugins/credentials/1.10/credentials.hpi
Downloading plugin: scm-api from https://updates.jenkins.io/download/plugins/scm-api/0.2/scm-api.hpi
Skipping optional dependency promoted-builds
Downloading plugin: ssh-credentials from https://updates.jenkins.io/download/plugins/ssh-credentials/1.6.1/ssh-credentials.hpi
 > ssh-credentials depends on credentials:1.9.4
 > scm-api has no dependencies
 > credentials has no dependencies
 > git-client depends on ssh-credentials:1.6.1

Cleaning up locks
 ---> ae816c8d41b7
```

**Comment by carlossg** [comment]
@ydubreuil I think it is better to have a way to install plugins without the overhead of Maven, given that it is working fairly well. 

I agree that install-plugins should mimic the UI installation, so

* installing latest: seems it's the way to go. 
* optional-plugins: does the UI install those too? It seems weird
* version conflicts: this is something to be solved by users by explicitly listing the plugins and versions they want in order to have a consistent build

**Comment by jmMeessen** [comment]
@carlossg 
I can confirm that the UI does not install the optional plugins.
I did my comparisons by comparing the `install-plugins` with the hand installed list retrieved with the curl command.

Jmm

**Comment by dduportal** [comment]
Does it seems an option to add the UI behavior to the jenkins-cli.jar ?
Or even better: a separated (but optional) jar that can be outside jenkins, to ensure having a unified behavior, and not spreading the effort maintaining different "programmatics" ways ?

@ydubreuil I love the way Maven manage deps, but I think that Java haters or 100 % purely no-Java won't try the effort :(

**Comment by ydubreuil** [comment]
> @ydubreuil I think it is better to have a way to install plugins without the overhead of Maven, given that it is working fairly well. 

@carlossg It was not working for my use case, that's why I tried with Maven in the first place. 

Regarding optional dependencies, I didn't say that they must be downloaded, but they must be used to create the dependency tree. If a plugin has a hard dependency that is an optional dependency of another plugin, the higher version of the dependency should be downloaded and that was not the case.

Anyway, always downloading latest versions of plugins fixes this problem, at the expense of not having a reproducible build. The script should be called `install-latest-plugins.sh`

> Does it seems an option to add the UI behavior to the jenkins-cli.jar ?
>  Or even better: a separated (but optional) jar that can be outside jenkins, to ensure having a unified behavior, and not spreading the effort maintaining different "programmatics" ways ?

Yeah, that would be the best option, but nobody step up to write such support.

> I love the way Maven manage deps, but I think that Java haters or 100 % purely no-Java won't try the effort :(
It's the Jenkins image what we speaking of, I hope people using it like Java and Maven at least a bit
