### ISSUE TITLE
tini-static-amd64 can't be download

### ISSUE THREAD

**Issue by etiaxie** [jenkinsci/docker#445]
### Docker commands that you execute
docker build -t donhui/jenkins .
### Actual result
RUN curl -fsSL https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static-amd64 -o /bin/tini && chmod +x /bin/tini \

the command will be failed for my network can't download the file tini-static-amd64, does't have any way to just pass this step

**Comment by dweomer** [comment]
Because Jenkins is a long-running process that starts up many subprocesses there is a need for zombie process reaping which is what `tini` provides. Since you are building the container yourself you can chose to remove it if you do not want it (you have the source). Be advised that you will need to modify the entry-point script as it assumes `tini` to be present as `/bin/tini`.

**Comment by carlossg** [comment]
this works fine here 

```
TINI_VERSION=0.13.2 curl -fsSL https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-static-amd64
```
