### ISSUE TITLE
Volume Mapping is not working with Jenkins compose file

### ISSUE THREAD

**Issue by anilk14** [jenkinsci/docker#490]
I am trying to create a jenkins and nexus integration using docker compose file. Where in my jenkins updated with few plugins using Dockerfile and volume created under /var/lib/jenkins/.

VOLUME ["/var/lib/jenkins/"]

in compose file am trying to map my volume to local store /opt/jenkins/

jenkins:
  build: ./jenkins
  ports:
    - 9090:8080
  volumes:      
    - /opt/jenkins/:/var/lib/jenkins/
But Nothing is copying to my persistence directory(/opt/jenkins/).

I can see in all my jenkins jobs created under <Volume_Id>/_data/jobs/ directory under some volume. not in my defined  volume /var/lib/jenkins/

**Comment by carlossg** [comment]
Because data is stored in /var/jenkins_home

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.
