### ISSUE TITLE
jenkinsci/jenkins 2.68 is not pushed to dockerhub

### ISSUE THREAD

**Issue by Meabed** [jenkinsci/docker#523]
Hi Guys,
jenkinsci/jenkins 2.68 is not pushed to dockerhub
https://hub.docker.com/r/jenkinsci/jenkins/tags/
Could we fix it.

**Comment by carlossg** [comment]
it could be because the shellcheck docker image was updated and broke the build.  Fixed now, but the deploy script would need to be re-ran

**Comment by rtyler** [comment]
@carlossg This looks more like a casualty I missed when added [dynamic agents to our trusted.ci environment](https://issues.jenkins-ci.org/browse/INFRA-1066).

This will necessitate a change to the `Jenkinsfile` to use credentials stored in Jenkins rather than those implicitly located on the agent machine. I'll fire up a PR for `master` and `alpine` branches.

**Comment by rtyler** [comment]
Everything has been re-run and the tags are updated on dockerhub
