### ISSUE TITLE
HTTP/2 support

### ISSUE THREAD

**Issue by Puneeth-n** [jenkinsci/docker#595]
Can we have HTTP/2 support in the docker lts images?

**Comment by oleg-nenashev** [comment]
What exactly are you missing? HTTP/2 support in Jenkins is available in the recent images though it's disabled by default. See https://github.com/jenkinsci/winstone/#http2-support

**Comment by oleg-nenashev** [comment]
CC @olamy

**Comment by Puneeth-n** [comment]
I couldn't find the alpn module inside the docker container for one.

**Comment by fcanela** [comment]
I am running into a issue with HTTP/2 too (https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/issues/136). I found no documentation about how can we enable HTTP/2 in the image. Is there any available?

**Comment by fcanela** [comment]
@oleg-nenashev I do not understand what do you mean with it being available in the images but disabled by default. I searched through the repositories without success.

As far as I am reading it looks like we have to manually install ALPN library inside the image, which seems to me a quite delicate operation as ALPN needs an specific version for each jdk revision.

**Comment by fcanela** [comment]
Hello. This issue is blocking us. We are afraid to manually install the library because the image would be very fagile as it is very jvm version dependant.

There was mentioned by @oleg-nenashev that HTTP/2 support was already in but disabled. He also provided an useful example for non-container installations in which we could to freeze the jvm version installed in new deployments so it becomes no issue.

Is there anything we could do to have a reliable Jenkins image with HTTP/2?

**Comment by carlossg** [comment]
I guess the ask here is to add the ALPN jar in the image, following the instructions in https://github.com/jenkinsci/winstone/#http2-support

**Comment by deiwin** [comment]
Any updates?

**Comment by shamil** [comment]
Any updates?

**Comment by oleg-nenashev** [comment]
Any contributions are welcome @shamil . Jenkins is a community-driven project, and we encourage everyone to submit pull requests.

**Comment by timja** [comment]
Closing given https://github.com/jenkinsci/docker/issues/955#issuecomment-884704714
