### ISSUE TITLE
: invalid option

### ISSUE THREAD

**Issue by chengfengpiaopiao** [jenkinsci/docker#615]
When I build a Dockerfile as a mirror and run it, this error occurs，please help me，thanks
The steps are as follows：
      docker build -t docker-jenkins .
      docker run -p 8080:8080 -p 50000:50000 docker-jenkins

**Comment by carlossg** [comment]
* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).

**Comment by morris821028** [comment]
I also encountered this problem.  Have you solved it? @chengfengpiaopiao . Can you share what's happened to it?  Thanks a lot.

**Comment by morris821028** [comment]
With my colleague help, the reason is from different line endings between Windows and Linux.  If you download this repository on Windows PC through git, the most users often get the Windows format in these scripts.  Dockerfile will copy windows format into a container, and then you use `docker run` to execute scripts in windows' line ending.  Finally, get 

```
git clone https://github.com/jenkinsci/docker.git jenkins
cd jenkins
docker build -t jenkins .
```

```
PS C:\Users\jenkins> docker run -p 8080:8080 jenkins
: invalid option
```

Simple solution is to transform these script in linux format as follows:

```
PS C:\Users\jenkins> git config core.autocrlf false
PS C:\Users\jenkins> git config core.eol lf
PS C:\Users\jenkins> del -recurse *
PS C:\Users\jenkins> git checkout .
```

Build again, and run successfully.

@carlossg , how to avoid these problems again for Windows users? Thanks a lot for my colleague.
