### ISSUE TITLE
/bin/tini in jenkins:lts was suddenly moved to /sbin/tini

### ISSUE THREAD

**Issue by dbsanfte** [jenkinsci/docker#629]
### Docker commands that you execute

Jenkins:lts, in merging in the tini branch, moved the tini executable from /bin/tini to /sbin/tini.

### Actual result

This unannounced change broke our init script.

### Expected outcome

Changes are tested before they are pushed to :lts, and breaking changes like this are announced ahead of time.

**Comment by carlossg** [comment]
alpine has moved tini to `/sbin/tini` and it's warning users still using `/bin/tini` that's why all the images have moved `tini` to that new location

If you just use `tini` it will work, which would be the preferred way IMHO

```
$ docker run -ti --rm --entrypoint tini jenkins/jenkins:lts --version
tini version 0.16.1 - git.0effd37
```

That said I'm not sure what guarantees people expect from this image, there are some known extension points like `install-plugins` but there are changes in the OS, like new debian, alpine, jdk versions and their libraries that are pulled from the official images in every new build

**Comment by mikemoate** [comment]
Actually the breaking change was caused by the switch to the alpine package, instead of the previous direct binary download into /bin (the switch happened in https://github.com/jenkinsci/docker/pull/579/files). That’s a significant behaviour change, not just catching up the latest Alpine changes.

I agree an LTS release shouldn’t push out a change like this without a clear announcement.

**Comment by carlossg** [comment]
> I agree an LTS release shouldn’t push out a change like this without a clear announcement.

I agree that there could be a changelog here, but I don't see how would that help in this case because you already get a decent error message `/bin/tini: no such file or directory`

About LTS, it doesn't mean that there are no breaking changes between LTS releases. I don't see how people can use `FROM jenkins/jenkins:lts` or any other of the _modifyable_ tags and not expect changes in parts of the image. 
If you want LTS benefits you need to stick to one of the explicit LTS versions, not just pick whatever the latest LTS is

**Comment by oleg-nenashev** [comment]
Hit it as well. 
@carlossg Would it be reasonable to add a symbolic link for compatibility?

**Comment by dbsanfte** [comment]
@carlossg I envisage a long tail of people coming to this thread complaining that their configured entrypoints don't work anymore. 

At the very least you should add a symbolic link to save yourself the trouble.

**Comment by carlossg** [comment]
adding a symlink will just delay the issue until it gets removed, fine with me if anyone wants to do it.
Added a changelog

**Comment by ndeloof** [comment]
@dbsanfte as you inherit from this image, why don't you just invoke the upstream entrypoint from your custom one ? Such compatibility issue would have been managed in the entrypoint.

**Comment by batmat** [comment]
@carlossg maybe we could do what was done in alpine 3.4, as was shown to me by @dduportal, put a temporary shim script, that will handle backward compatibility and spit a big fat warning:

```WARNING: Tini has been relocated to /sbin/tini.
Please update your scripts to use /sbin/tini going forward.
/usr/bin/tini has been preserved for backwards compatibility in Alpine 3.4,
but WILL BE REMOVED in Alpine 3.5. (or Jenkins 2.107.1 or something like this for our case)
```

**Comment by batmat** [comment]
Even better, add `sleep 120` or more after this log so that it does not prevent the service from starting, but is more noticeable.

**Comment by batmat** [comment]
Proposed in https://github.com/jenkinsci/docker/pull/650
