### ISSUE TITLE
Java missing from image?

### ISSUE THREAD

**Issue by larsskj** [jenkinsci/docker#835]
This image fails to run on our machine in release 2.179 and 2.180. 2.178 runs fine, but when I upgrade, the container keeps restarting and the logs show:

`/usr/local/bin/jenkins.sh: line 35: exec: java: not found`

That sounds a bit weird to me...

Downgrading to 2.178 makes Jenkins work again.

**Comment by oleg-nenashev** [comment]
Likely it was a change in the upstream image (switch to AdoptOpenJDK in the upstream)?
CC @jenkinsci/sig-platform

**Comment by MarkEWaite** [comment]
I believe that Oleg is correct.  The [jenkinsci/jenkins image is deprecated](https://hub.docker.com/r/jenkinsci/jenkins) in favor of the [community maintained jenkins/jenkins image](https://hub.docker.com/r/jenkins/jenkins/).  

When I run the community maintained image:

```
$ docker run -p 8080:8080 --rm -i -t jenkins/jenkins:2.180
```

I am able to connect to that Jenkins image and it works as expected.

When I try to run the dockerhub maintained image:

```
$ docker run -p 8080:8080 --rm -i -t jenkinsci/jenkins:2.180
Unable to find image 'jenkinsci/jenkins:2.180' locally
docker: Error response from daemon: manifest for jenkinsci/jenkins:2.180 not found.
See 'docker run --help'.
```

In order to reduce confusion, I believe the team at Dockerhub wisely decided to stop publishing the deprecated images of jenkinsci/jenkins.  The last tags I see on that site are for 2.150.1.

Maybe you're building from your own Dockerfile rather than using the tagged image?  If so, then you probably want to compare your private Dockerfile to the upstream image, as recommended by @oleg-nenashev .

**Comment by larsskj** [comment]
Oops - sorry - I'm in the wrong place.
It _is_ jenkins/jenkins, I'm using - not jenkinsci/jenkins.
And apparently I've found the reason for the problem: Somebody has setup an environment variable for the container pointing to the wrong Java...
Sorry for the confusion.
