### ISSUE TITLE
Built-in plugins can't be upgraded using plugins.txt

### ISSUE THREAD

**Issue by TwoSlick** [jenkinsci/docker#86]
When I add a newer version of a built-in plugin like javadoc, to my plugins.txt file, I've noticed that it doesn't show up when the container is run.  I specify javadoc:1.3 in the plugins.txt file, and build my image.  I've verified that building the image downloads the correct version, and places it in the /usr/share/jenkins/ref/plugins directory.  When the container is run, the jenkins.sh script does in fact copy it into /var/jenkins_home/plugins directory.  However, when the jenkins.war file is run, it extracts the built-in version, and overwrites the one I wanted.  This results in the older version being used.

**Comment by chorrylan** [comment]
This seems to be the working-as-designed' behaviour for the jenkins.sh script.
On RUN it copies files (including plugins) across from the ref directory to jenkins_home only if they don't already exist.

Maybe... if the script checked for a specific/single switch, 
eg  a file ${JENKINS_HOME}/.docker-on-run-complete
that it creates after completing the initialization logic like copying plugins, instead of checking each and every file.

**Comment by chorrylan** [comment]
Extracting the plugins from the war into /usr/share/jenkins/ref/plugins and then deleting them from the war looks to be a reasonable workaround 

eg see: 
https://github.com/GeoscienceAustralia/jenkins-docker/commit/086a10f8304338fc24d561af11016a57a6ee10c2

**Comment by TwoSlick** [comment]
That looks like a pretty good way of doing it.

**Comment by carlossg** [comment]
An option would be for the official image to extract the plugins into `ref` and delete them from the war, that way downstream images would be able to overwrite them

**Comment by david-resnick** [comment]
+1 on getting this fixed.

**Comment by ndeloof** [comment]
Simplest solution would be to create a `pinned` file for plugins that get installed based on plugin.txt

**Comment by ndeloof** [comment]
fixed by https://github.com/jenkinsci/docker/pull/98
