### ISSUE TITLE
install-plugins.sh - auto-load plugins.txt from a location

### ISSUE THREAD

**Issue by HariSekhon** [jenkinsci/docker#939]
Is it possible to bind mount a plugins.txt in to the jenkins container at a standard location and if detected have install-plugins.sh called automatically on it and restarted as part of container initialization?

I work around this right now by having a script manually exec install-plugins.sh and then restart the container to pick up the changes, but am thinking this would be better done in a standard way?

**Comment by oleg-nenashev** [comment]
@HariSekhon we had a discussion of such feature for the Jenkins core. We plan to add https://github.com/jenkinsci/plugin-installation-manager-tool (or equivalent) to the startup logic so that it pick up the file in the root if it is present. Anybody can implement a similar befavior in the Docker image by tweaking the script

**Comment by oleg-nenashev** [comment]
One difference between the approaches in the runtime behavior. "automatic restart on change" is something we did not discuss/consider. I am definitely -1 for making it a default behavior, but it can be done as an opt-in feature.

CC @timja @Jetersen

**Comment by timja** [comment]
install-plugins.sh is deprecated for removal, no changes to it will be done
