### ISSUE TITLE
Preinstalling plugins don't download latest

### ISSUE THREAD

**Issue by cryptolukas** [jenkinsci/docker#979]
# Issues and Contributing

Please note that only issues related to this Docker image will be addressed here.

* If you have Docker related issues, please ask in the [Docker user mailing list](https://groups.google.com/forum/#!forum/docker-user).
* If you have Jenkins related issues, please ask in the [Jenkins mailing lists](https://jenkins-ci.org/content/mailing-lists).
* If you are not sure, then this is probably not the place to create an issue and you should use any of the previously mentioned mailing lists.

If after going through the previous checklist you still think you should create an issue here please provide:

### Docker commands that you execute
```
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
```
### Actual result
a.e. some plugins with installed version in the docker build context
branch-api:2.5.5
configuration-as-code:1.36
git:4.2.0
gitlab-oauth:1.5
### Expected outcome
Like the UI tells me I should have the following versions:
branch-api:2.5.9
configuration-as-code:1.4.3
git:4.3.0
gitlab-oauth:1.6

### Have you tried a non-dockerized Jenkins and get the expected outcome?
No I didn't.
### Output of `docker version`
`Docker version 19.03.12-ce, build 48a66213fe`

**Comment by timja** [comment]
That's due to a bug in the install-plugins.sh script and a change on the infrastructure side where the latest folder doesn't get updated anymore.

The easiest change is to not use the install-plugins script and use the new plugin manager CLI instead, it'll be shipped by default as soon as someone merges https://github.com/jenkinsci/docker/pull/971 cc @jenkinsci/team-docker-packaging.

and in the meantime you can add it yourselves with:
https://github.com/hmcts/cnp-jenkins-docker/blob/master/jenkins/Dockerfile#L5-L9

**Comment by timja** [comment]
Fixed by https://github.com/jenkins-infra/update-center2/pull/436
