### ISSUE TITLE
Option to disable DNS caching for docker image

### ISSUE THREAD

**Issue by realies** [jenkinsci/docker#993]
We have an instance of a SSH target that changes their IP fairly frequently. The DNS resolver caches those and consecutive requests require for the Jenkins docker image to be restarted so the resolver can fetch the correct IP. Adding these options to the compose file does not help, can there be an implementation of this that does not require modifying the config files of the JVM (/usr/local/openjdk-8/jre/lib/security/java.security)?
```
    environment:
      - JAVA_OPTS='-Dsun.net.inetaddr.ttl=0'
      - JAVA_OPTS='-Dnetworkaddress.cache.ttl=0'
```

**Comment by timja** [comment]
You can just set the required java opts

**Comment by realies** [comment]
@timja, please provide an example.

**Comment by timja** [comment]
Try just -Dsun.net.inetaddr.ttl=0

If you used your example above you would have overwritten the first one with the second and it wouldn’t be used.

otherwise you should extend the docker image and modify the security file which is safe because Jenkins is the only application using the above.

Also is this happening on the controller or an agent? Maybe you need to adjust the agent JVM and not the controller if you’re using distributed builds
