### ISSUE TITLE
jenkins-plugin-cli: not found

### ISSUE THREAD

**Issue by dtrunk90** [jenkinsci/docker#994]
Trying to build a simple Dockerfile as stated in the README:

```
FROM jenkins/jenkins:lts
RUN jenkins-plugin-cli --plugins \
	workflow-aggregator
```

But getting:
```
Step 2/2 : RUN jenkins-plugin-cli --plugins 	workflow-aggregator
 ---> Running in 7cf716720a92
/bin/sh: 1: jenkins-plugin-cli: not found
```

I could use the Shell script but I don't want to stick with a deprecated script: https://github.com/jenkinsci/docker/blob/master/install-plugins.sh#L23

**Comment by sureshchoudhary** [comment]
Hi @dtrunk90 this could have been a temporary issue. I simply copy-pasted your dockerfile and it worked just fine for me. It might be helpful to reproduce errors with exact docker tags (e.g. jenkins/jenkins:2.259) so that they can be reproduced reliably and makes it easy to see if it was fixed in newer versions.

**Comment by dtrunk90** [comment]
Yes, it's working now. Maybe the lts image i used at that time was too old. Strange.
